### PR TITLE
Fixed package update check on update.sh

### PR DESCRIPTION
**Pull request by JeppeX**
The path for executing _checkupdates_ was missing. This commit fixes just that.

### CODE REVIEW

**Comment by JuanVqz** [comment]
@JeppeX thank you, I was searching about this issue, I tested the full URL that you fixed but it still not working, so
I noticed the checkupdates script uses `pacman`, do you know how can I make it works with ubuntu? Thank you!

**Comment by JeppeX** [comment]
I found the following one-liner from [stackoverflow](https://serverfault.com/questions/287966/how-to-get-the-number-of-available-updates-on-an-ubuntu-system-as-a-normal-user): `/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1`

Just update line 6 from update.sh accordingly: `get_total_updates() { UPDATES=$(/usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1); }`

**Comment by JuanVqz** [comment]
@JeppeX I thought it works because it shows `3 Updates` then I ran `apt-get update` and `apt-get upgrade` but the `3 Updates` still there.

screenshot_2020-12-09_10:45:15

**Comment by JeppeX** [comment]
@JuanVqz Try running `/usr/lib/update-notifier/apt-check 2>&1` in bash. If it shows something other than "0;0" then your system is not fully upgraded or the `apt_check` script itself is not working. I'm not an apt pro, but I've heard there are commands such as `apt full-upgrade` and `apt dist-upgrade` that are supposed to "upgrade more" than a regular upgrade command. If you have the default config in updates.sh, it should check every 10s if you have updated.

**Comment by JuanVqz** [comment]
> @JuanVqz Try running `/usr/lib/update-notifier/apt-check 2>&1` in bash. If it shows something other than "0;0" then your system is not fully upgraded or the `apt_check` script itself is not working. I'm not an apt pro, but I've heard there are commands such as `apt full-upgrade` and `apt dist-upgrade` that are supposed to "upgrade more" than a regular upgrade command. If you have the default config in updates.sh, it should check every 10s if you have updated.

@JeppeX thank you again for your support, yes, I ran the `apt-check` in my terminal and it shows `3:0%`, yes maybe the `apt_check` is failing, I received more updates I had 7 updates then I ran `apt-get update` then returns to `3` but I'm glad having it as it is.

**Comment by JuanVqz** [comment]
@JeppeX Again me, just to following up with my "issue" I am using ubuntu mate and I changed to that Windows manager and you are right I had had updates, I did and now I'm not seen `3 Updates` counter in the polybar bar, thank you!

**Comment by JuanVqz** [comment]
just to let you know, I noticed that the `apt-check` returns this format `3;1%` which the first `3` means the `upgradable` packages and the `1` means the `updatable` packages.

So, if I were run `apt-get upgrade` the `3` digit will be `0`.
 if I were run `apt-get update` the `1` digit will be `0`

**Pull request closed without merging**
